To get started do the following:

https://github.com/grails-guides/grails-google-cloud/archive/master.zip[Download]
and unzip the source or Clone the Git repository:

[source, bash]
----
git clone https://github.com/grails-guides/grails-google-cloud.git
----

The Grails guides repositories contain two folders:

- `initial` Initial project. A simple Grails app with additional some code to give you a head-start.

- `complete` A completed example. It is the result of working through the steps presented by the guide and applying those changes to the initial folder.

To complete the guide, go to the initial folder

`cd initial`

and follow the instructions in the next sections.

or you can go right to the completed example:

`cd complete`

Although you can go right to the completed example, in order to deploy the app you
would need to complete several configuration steps in Google Cloud:

- Signup for Cloud SDK and install Cloud SDK.

- Initialize an App Engine application within the current Google Cloud project.

- Create a Mysql Database in an instance of Cloud SQL.

- Enable Cloud Datastore API for the project

Moreover, You would need to modify your `application.yml` configuration to point
to the correct Cloud SQL database and Cloud Storage Bucket. Checkout the guide
steps for more details.
