runtime: java
env: flex

runtime_config:
    jdk: openjdk8
    server: jetty9

health_check:
    enable_health_check: True
    check_interval_sec: 8
    timeout_sec: 4
    unhealthy_threshold: 2
    healthy_threshold: 2

resources:
    cpu: 1
    memory_gb: 2.3

manual_scaling:
    instances: 1
